SQL> SET SERVEROUTPUT ON;
SQL> CREATE OR REPLACE PACKAGE ACCOUNTOPERATIONS IS
  2      PROCEDURE OPENNEWACCOUNT(
  3          P_ACCOUNT_ID IN ACCOUNTS.ACCOUNTID%TYPE,
  4          P_CUSTOMER_ID IN ACCOUNTS.CUSTOMERID%TYPE,
  5          P_ACCOUNT_TYPE IN ACCOUNTS.ACCOUNTTYPE%TYPE,
  6          P_BALANCE IN ACCOUNTS.BALANCE%TYPE
  7      );
  8  
  9      PROCEDURE CLOSEACCOUNT(
 10          P_ACCOUNT_ID IN ACCOUNTS.ACCOUNTID%TYPE
 11      );
 12  
 13      FUNCTION GETTOTALBALANCE(
 14          P_CUSTOMER_ID IN ACCOUNTS.CUSTOMERID%TYPE
 15      ) RETURN NUMBER;
 16  END ACCOUNTOPERATIONS;
 17  /

Package created.

SQL> 
SQL> SET SERVEROUTPUT ON;
SQL> CREATE OR REPLACE PACKAGE BODY ACCOUNTOPERATIONS IS
  2  
  3      PROCEDURE OPENNEWACCOUNT(
  4          P_ACCOUNT_ID IN ACCOUNTS.ACCOUNTID%TYPE,
  5          P_CUSTOMER_ID IN ACCOUNTS.CUSTOMERID%TYPE,
  6          P_ACCOUNT_TYPE IN ACCOUNTS.ACCOUNTTYPE%TYPE,
  7          P_BALANCE IN ACCOUNTS.BALANCE%TYPE
  8      ) IS
  9      BEGIN
 10          INSERT INTO ACCOUNTS (ACCOUNTID, CUSTOMERID, ACCOUNTTYPE, BALANCE, LASTMODIFIED)
 11          VALUES (P_ACCOUNT_ID, P_CUSTOMER_ID, P_ACCOUNT_TYPE, P_BALANCE, SYSDATE);
 12      END OPENNEWACCOUNT;
 13  
 14      PROCEDURE CLOSEACCOUNT(
 15          P_ACCOUNT_ID IN ACCOUNTS.ACCOUNTID%TYPE
 16      ) IS
 17      BEGIN
 18          DELETE FROM ACCOUNTS
 19          WHERE ACCOUNTID = P_ACCOUNT_ID;
 20      END CLOSEACCOUNT;
 21  
 22      FUNCTION GETTOTALBALANCE(
 23          P_CUSTOMER_ID IN ACCOUNTS.CUSTOMERID%TYPE
 24      ) RETURN NUMBER IS
 25          V_TOTAL_BALANCE NUMBER;
 26      BEGIN
 27          SELECT SUM(BALANCE) INTO V_TOTAL_BALANCE
 28          FROM ACCOUNTS
 29          WHERE CUSTOMERID = P_CUSTOMER_ID;
 30          RETURN V_TOTAL_BALANCE;
 31      END GETTOTALBALANCE;
 32  
 33  END ACCOUNTOPERATIONS;
 34  /

Package body created.

SQL> SPOOL OFF
