SQL> SET SERVEROUTPUT ON;
SQL> CREATE OR REPLACE PACKAGE EMPLOYEEMANAGEMENT IS
  2      PROCEDURE HIREEMPLOYEE(
  3          P_EMPLOYEE_ID IN EMPLOYEES.EMPLOYEEID%TYPE,
  4          P_NAME IN EMPLOYEES.NAME%TYPE,
  5          P_POSITION IN EMPLOYEES.POSITION%TYPE,
  6          P_SALARY IN EMPLOYEES.SALARY%TYPE,
  7          P_DEPARTMENT IN EMPLOYEES.DEPARTMENT%TYPE,
  8          P_HIRE_DATE IN EMPLOYEES.HIREDATE%TYPE
  9      );
 10  
 11      PROCEDURE UPDATEEMPLOYEEDETAILS(
 12          P_EMPLOYEE_ID IN EMPLOYEES.EMPLOYEEID%TYPE,
 13          P_NAME IN EMPLOYEES.NAME%TYPE,
 14          P_POSITION IN EMPLOYEES.POSITION%TYPE,
 15          P_SALARY IN EMPLOYEES.SALARY%TYPE,
 16          P_DEPARTMENT IN EMPLOYEES.DEPARTMENT%TYPE
 17      );
 18  
 19      FUNCTION CALCULATEANNUALSALARY(
 20          P_EMPLOYEE_ID IN EMPLOYEES.EMPLOYEEID%TYPE
 21      ) RETURN NUMBER;
 22  END EMPLOYEEMANAGEMENT;
 23  /

Package created.

SQL> 
SQL> SET SERVEROUTPUT ON;
SQL> CREATE OR REPLACE PACKAGE BODY EMPLOYEEMANAGEMENT IS
  2  
  3      PROCEDURE HIREEMPLOYEE(
  4          P_EMPLOYEE_ID IN EMPLOYEES.EMPLOYEEID%TYPE,
  5          P_NAME IN EMPLOYEES.NAME%TYPE,
  6          P_POSITION IN EMPLOYEES.POSITION%TYPE,
  7          P_SALARY IN EMPLOYEES.SALARY%TYPE,
  8          P_DEPARTMENT IN EMPLOYEES.DEPARTMENT%TYPE,
  9          P_HIRE_DATE IN EMPLOYEES.HIREDATE%TYPE
 10      ) IS
 11      BEGIN
 12          INSERT INTO EMPLOYEES (EMPLOYEEID, NAME, POSITION, SALARY, DEPARTMENT, HIREDATE)
 13          VALUES (P_EMPLOYEE_ID, P_NAME, P_POSITION, P_SALARY, P_DEPARTMENT, P_HIRE_DATE);
 14      END HIREEMPLOYEE;
 15  
 16      PROCEDURE UPDATEEMPLOYEEDETAILS(
 17          P_EMPLOYEE_ID IN EMPLOYEES.EMPLOYEEID%TYPE,
 18          P_NAME IN EMPLOYEES.NAME%TYPE,
 19          P_POSITION IN EMPLOYEES.POSITION%TYPE,
 20          P_SALARY IN EMPLOYEES.SALARY%TYPE,
 21          P_DEPARTMENT IN EMPLOYEES.DEPARTMENT%TYPE
 22      ) IS
 23      BEGIN
 24          UPDATE EMPLOYEES
 25          SET NAME = P_NAME,
 26              POSITION = P_POSITION,
 27              SALARY = P_SALARY,
 28              DEPARTMENT = P_DEPARTMENT
 29          WHERE EMPLOYEEID = P_EMPLOYEE_ID;
 30      END UPDATEEMPLOYEEDETAILS;
 31  
 32      FUNCTION CALCULATEANNUALSALARY(
 33          P_EMPLOYEE_ID IN EMPLOYEES.EMPLOYEEID%TYPE
 34      ) RETURN NUMBER IS
 35          V_SALARY EMPLOYEES.SALARY%TYPE;
 36      BEGIN
 37          SELECT SALARY INTO V_SALARY
 38          FROM EMPLOYEES
 39          WHERE EMPLOYEEID = P_EMPLOYEE_ID;
 40          RETURN V_SALARY * 12; -- Assuming salary is monthly
 41      END CALCULATEANNUALSALARY;
 42  
 43  END EMPLOYEEMANAGEMENT;
 44  /

Package body created.

SQL> SPOOL OFF
