SQL> SET SERVEROUTPUT ON;
SQL> CREATE OR REPLACE PACKAGE CustomerManagement IS
  2      PROCEDURE AddNewCustomer(
  3          p_customer_id IN CUSTOMERS.CUSTOMERID%TYPE,
  4          p_name IN CUSTOMERS.NAME%TYPE,
  5          p_dob IN CUSTOMERS.DOB%TYPE,
  6          p_balance IN CUSTOMERS.BALANCE%TYPE
  7      );
  8  
  9      PROCEDURE UpdateCustomerDetails(
 10          p_customer_id IN CUSTOMERS.CUSTOMERID%TYPE,
 11          p_name IN CUSTOMERS.NAME%TYPE,
 12          p_dob IN CUSTOMERS.DOB%TYPE,
 13          p_balance IN CUSTOMERS.BALANCE%TYPE
 14      );
 15  
 16      FUNCTION GetCustomerBalance(
 17          p_customer_id IN CUSTOMERS.CUSTOMERID%TYPE
 18      ) RETURN CUSTOMERS.BALANCE%TYPE;
 19  END CustomerManagement;
 20  /

Package created.

SQL> 
SQL> SET SERVEROUTPUT ON;
SQL> CREATE OR REPLACE PACKAGE BODY CUSTOMERMANAGEMENT IS
  2  
  3      PROCEDURE ADDNEWCUSTOMER(
  4          P_CUSTOMER_ID IN CUSTOMERS.CUSTOMERID%TYPE,
  5          P_NAME IN CUSTOMERS.NAME%TYPE,
  6          P_DOB IN CUSTOMERS.DOB%TYPE,
  7          P_BALANCE IN CUSTOMERS.BALANCE%TYPE
  8      ) IS
  9      BEGIN
 10          INSERT INTO CUSTOMERS (CUSTOMERID, NAME, DOB, BALANCE, LASTMODIFIED)
 11          VALUES (P_CUSTOMER_ID, P_NAME, P_DOB, P_BALANCE, SYSDATE);
 12      END ADDNEWCUSTOMER;
 13  
 14      PROCEDURE UPDATECUSTOMERDETAILS(
 15          P_CUSTOMER_ID IN CUSTOMERS.CUSTOMERID%TYPE,
 16          P_NAME IN CUSTOMERS.NAME%TYPE,
 17          P_DOB IN CUSTOMERS.DOB%TYPE,
 18          P_BALANCE IN CUSTOMERS.BALANCE%TYPE
 19      ) IS
 20      BEGIN
 21          UPDATE CUSTOMERS
 22          SET NAME = P_NAME,
 23              DOB = P_DOB,
 24              BALANCE = P_BALANCE,
 25              LASTMODIFIED = SYSDATE
 26          WHERE CUSTOMERID = P_CUSTOMER_ID;
 27      END UPDATECUSTOMERDETAILS;
 28  
 29      FUNCTION GETCUSTOMERBALANCE(
 30          P_CUSTOMER_ID IN CUSTOMERS.CUSTOMERID%TYPE
 31      ) RETURN CUSTOMERS.BALANCE%TYPE IS
 32          V_BALANCE CUSTOMERS.BALANCE%TYPE;
 33      BEGIN
 34          SELECT BALANCE INTO V_BALANCE
 35          FROM CUSTOMERS
 36          WHERE CUSTOMERID = P_CUSTOMER_ID;
 37          RETURN V_BALANCE;
 38      END GETCUSTOMERBALANCE;
 39  
 40  END CUSTOMERMANAGEMENT;
 41  /

Package body created.

SQL> SPOOL OFF
