SQL> SET SERVEROUTPUT ON;
SQL> DECLARE
  2      CURSOR CUR_LOANS IS
  3          SELECT LOANID, INTERESTRATE
  4          FROM LOANS;
  5  
  6      V_LOAN_ID LOANS.LOANID%TYPE;
  7      V_INTEREST_RATE LOANS.INTERESTRATE%TYPE;
  8      V_NEW_INTEREST_RATE NUMBER;
  9      V_NEW_POLICY NUMBER := 2;
 10  
 11      FUNCTION CALCULATENEWINTERESTRATE(OLD_RATE NUMBER) RETURN NUMBER IS
 12      BEGIN
 13          RETURN OLD_RATE * (1 + (V_NEW_POLICY / 100));
 14      END CALCULATENEWINTERESTRATE;
 15  BEGIN
 16      OPEN CUR_LOANS;
 17  
 18      LOOP
 19          FETCH CUR_LOANS INTO V_LOAN_ID, V_INTEREST_RATE;
 20          EXIT WHEN CUR_LOANS%NOTFOUND;
 21  
 22          V_NEW_INTEREST_RATE := CALCULATENEWINTERESTRATE(V_INTEREST_RATE);
 23  
 24          UPDATE LOANS
 25          SET INTERESTRATE = V_NEW_INTEREST_RATE
 26          WHERE LOANID = V_LOAN_ID;
 27  
 28          DBMS_OUTPUT.PUT_LINE('Loan ID: ' || V_LOAN_ID || ' interest rate updated to ' || V_NEW_INTEREST_RATE);
 29      END LOOP;
 30  
 31      CLOSE CUR_LOANS;
 32  
 33      COMMIT;
 34  END;
 35  /
Loan ID: 1 interest rate updated to 5.1                                         

PL/SQL procedure successfully completed.

SQL> SPOOL OFF
